# Generated by Django 6.0.6 on 2026-07-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sitio', models.CharField(default='COLFENIX GPS', max_length=100)),
                ('descripcion_sidebar', models.CharField(blank=True, default='Centro de operaciones', help_text='Subtítulo bajo el nombre del sitio, en el logo del sidebar.', max_length=150)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/')),
                ('mostrar_reloj_topbar', models.BooleanField(default=True)),
                ('mostrar_tema_topbar', models.BooleanField(default=True)),
                ('mostrar_alertas_topbar', models.BooleanField(default=True)),
                ('mostrar_estado_sistema_topbar', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
