# Generated by Django 6.0.6 on 2026-07-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('etiqueta', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('vista', 'Vista'), ('accion', 'Acción')], max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'categoria', 'etiqueta'],
            },
        ),
    ]
