# Generated by Django 6.0.6 on 2026-06-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_area', models.CharField(max_length=200, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_index=True, default='ACTIVO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_novedad', models.CharField(editable=False, max_length=100, unique=True)),
                ('conductor', models.CharField(max_length=150)),
                ('nas', models.CharField(max_length=100)),
                ('pasajeros_reportados', models.PositiveIntegerField(default=0)),
                ('tipo_indicador', models.CharField(choices=[('Factor_de_riesgo', 'Factor de Riesgo'), ('Factor_de_distraccion', 'Factor de Distracción'), ('Normas_internas', 'Normas Internas'), ('Solicitud_externa', 'Solicitud Externa'), ('Novedad_especifica', 'Novedad Específica')], max_length=200)),
                ('fecha_novedad', models.DateField()),
                ('fecha_solicitud', models.DateField()),
                ('fecha_recepcion_dd', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_revision', models.DateTimeField(blank=True, null=True)),
                ('estado_dd', models.CharField(choices=[('PENDIENTE_DD', 'PENDIENTE DD'), ('ENCOLADO', 'ENCOLADO'), ('EN_REVISION', 'EN REVISION'), ('TERMINADO', 'TERMINADO')], default='PENDIENTE_DD', max_length=20)),
                ('respuesta_novedad', models.CharField(blank=True, choices=[('Positiva', 'Positiva'), ('Negativa', 'Negativa')], max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_novedad', models.CharField(choices=[('Pendiente_por_responder', 'Pendiente por responder'), ('Completado', 'Completado'), ('Informacion_incompleta', 'Información incompleta')], default='Pendiente_por_responder', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
