# Generated by Django 6.0.6 on 2026-06-17 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Informes', '0002_initial'),
        ('Vehiculo', '0001_initial'),
        ('novedades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='novedades',
            name='analista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novedades',
            name='area_solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='Cliente.area'),
        ),
        migrations.AddField(
            model_name='novedades',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='Cliente.cliente'),
        ),
        migrations.AddField(
            model_name='novedades',
            name='grupo_flota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='Vehiculo.grupoflota'),
        ),
        migrations.AddField(
            model_name='novedades',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='Vehiculo.ruta'),
        ),
        migrations.AddField(
            model_name='novedades',
            name='tipo_informe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='Informes.tipoinforme'),
        ),
        migrations.AddField(
            model_name='novedades',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='Vehiculo.vehiculo'),
        ),
    ]
