# Generated by Django 5.2.7 on 2026-06-23 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ruta',
        ),
    ]
