# Generated by Django 6.0.6 on 2026-06-25 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0003_delete_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedades',
            name='tipo_indicador',
        ),
    ]
