# Generated by Django 6.0.6 on 2026-06-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0004_remove_novedades_tipo_indicador'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedades',
            name='nivel_prioridad',
            field=models.CharField(choices=[('Prioridad_Alta', 'Prioridad Alta'), ('Prioridad_Media', 'Prioridad Media'), ('Prioridad_Baja', 'Prioridad Baja')], max_length=50, null=True),
        ),
    ]
