# Generated by Django 6.0.6 on 2026-07-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0005_novedades_nivel_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedades',
            name='nivel_prioridad',
            field=models.CharField(choices=[('Prioridad_Alta', 'Prioridad Alta'), ('Prioridad_Media', 'Prioridad Media'), ('Prioridad_Baja', 'Prioridad Baja')], editable=False, max_length=50, null=True),
        ),
    ]
