# Generated by Django 6.0.6 on 2026-07-04 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_area_abreviatura'),
        ('Informes', '0005_alter_tipoinforme_nivel_prioridad'),
        ('Vehiculo', '0001_initial'),
        ('novedades', '0007_delete_areasolicitante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AreaSolicitante',
        ),
        migrations.AlterField(
            model_name='novedades',
            name='codigo_novedad',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='novedades',
            name='nas',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='novedades',
            index=models.Index(fields=['estado_novedad'], name='novedades_n_estado__b6009c_idx'),
        ),
        migrations.AddIndex(
            model_name='novedades',
            index=models.Index(fields=['estado_dd'], name='novedades_n_estado__35c0f0_idx'),
        ),
        migrations.AddIndex(
            model_name='novedades',
            index=models.Index(fields=['fecha_novedad'], name='novedades_n_fecha_n_de135d_idx'),
        ),
        migrations.AddIndex(
            model_name='novedades',
            index=models.Index(fields=['cliente', 'estado_novedad'], name='novedades_n_cliente_cbab16_idx'),
        ),
    ]
