# Generated by Django 6.0.6 on 2026-07-13 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_area_abreviatura'),
        ('novedades', '0008_delete_areasolicitante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsecutivosCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.PositiveIntegerField(default=0)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consecutivo', to='Cliente.cliente')),
            ],
        ),
    ]
