# Generated by Django 6.0.6 on 2026-07-25 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0009_consecutivoscliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoNegativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Motivo de negativa',
                'verbose_name_plural': 'Motivos de negativa',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='novedades',
            name='detalle_motivo_negativo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='motivo_negativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='novedades.motivonegativo'),
        ),
        migrations.CreateModel(
            name='NovedadEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(max_length=50)),
                ('valor_anterior', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_nuevo', models.CharField(blank=True, max_length=255, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='novedades.novedades')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_novedad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de novedad',
                'verbose_name_plural': 'Eventos de novedad',
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='NovedadEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='novedades/evidencia/')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='novedades.novedades')),
            ],
            options={
                'verbose_name': 'Evidencia de novedad',
                'verbose_name_plural': 'Evidencias de novedad',
                'ordering': ['creado'],
            },
        ),
    ]
