# Generated by Django 6.0.6 on 2026-07-25 01:12

from django.db import migrations

MOTIVOS_INICIALES = [
    (
        "DVR no enciende",
        "El equipo no responde al intentar encenderlo o revisarlo en sitio.",
    ),
    (
        "Sin grabación del día solicitado",
        "La DVR enciende y responde, pero no cuenta con registros para la fecha solicitada.",
    ),
    (
        "Pila dañada — hora del equipo incorrecta",
        "La pila de respaldo está agotada y la DVR guarda la grabación con la fecha/hora de fábrica, no la real.",
    ),
]


def sembrar_motivos(apps, schema_editor):
    MotivoNegativo = apps.get_model('novedades', 'MotivoNegativo')
    for nombre, descripcion in MOTIVOS_INICIALES:
        MotivoNegativo.objects.get_or_create(
            nombre=nombre,
            defaults={"descripcion": descripcion},
        )


def eliminar_motivos(apps, schema_editor):
    MotivoNegativo = apps.get_model('novedades', 'MotivoNegativo')
    MotivoNegativo.objects.filter(
        nombre__in=[nombre for nombre, _ in MOTIVOS_INICIALES]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0010_motivonegativo_novedades_detalle_motivo_negativo_and_more'),
    ]

    operations = [
        migrations.RunPython(sembrar_motivos, eliminar_motivos),
    ]
