# Generated by Django 6.0.6 on 2026-07-28 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0011_seed_motivos_negativos'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.BooleanField(default=True)),
                ('martes', models.BooleanField(default=True)),
                ('miercoles', models.BooleanField(default=True)),
                ('jueves', models.BooleanField(default=True)),
                ('viernes', models.BooleanField(default=True)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('hora_inicio', models.TimeField(default=datetime.time(8, 0))),
                ('hora_fin', models.TimeField(default=datetime.time(18, 0))),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horario laboral',
                'verbose_name_plural': 'Horario laboral',
            },
        ),
    ]
