# Generated by Django 6.0.6 on 2026-07-28 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0013_backfill_fechas_estado_dd'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoPositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Motivo de positiva',
                'verbose_name_plural': 'Motivos de positiva',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='novedades',
            name='detalle_motivo_positivo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='motivo_positivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='novedades.motivopositivo'),
        ),
    ]
