# Generated by Django 6.0.6 on 2026-07-29 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehiculo', '0002_dispositivodvr'),
        ('novedades', '0017_resincronizar_consecutivos_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedades',
            name='dispositivo_dvr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades', to='Vehiculo.dispositivodvr'),
        ),
    ]
