# Generated by Django 6.0.6 on 2026-07-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0018_novedades_dispositivo_dvr'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedades',
            name='fecha_ingreso_dvr',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='fecha_salida_dvr',
            field=models.DateField(blank=True, null=True),
        ),
    ]
