# Generated by Django 6.0.6 on 2026-07-30 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0019_novedades_fecha_ingreso_dvr_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('track', models.CharField(choices=[('ANALISTA', 'Analista (revisión interna)'), ('CLIENTE', 'Cliente (portal externo)')], max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, help_text='Subtítulo mostrado bajo el nombre del paso en el asistente.', max_length=250)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición dentro de su track (analista o cliente).')),
                ('activo', models.BooleanField(default=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etapa del flujo',
                'verbose_name_plural': 'Etapas del flujo',
                'ordering': ['track', 'orden'],
            },
        ),
        migrations.AddField(
            model_name='novedades',
            name='comentario_cliente',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='fecha_respuesta_cliente',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='novedades',
            name='respondido_por_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='novedades_respondidas_cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novedades',
            name='respuesta_cliente',
            field=models.CharField(blank=True, choices=[('Conforme', 'Conforme'), ('No_conforme', 'No conforme')], max_length=20, null=True),
        ),
    ]
