# Generated by Django 6.0.6 on 2026-07-30 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_area_abreviatura'),
        ('Informes', '0014_tipoinforme_tiempo_maximo_horas'),
        ('Vehiculo', '0003_configuraciondvr_and_more'),
        ('novedades', '0021_seed_etapas_flujo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='novedades',
            index=models.Index(fields=['vehiculo', 'tipo_informe'], name='novedades_n_vehicul_f233c1_idx'),
        ),
    ]
