# Generated by Django 6.0.6 on 2026-07-30 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_area_abreviatura'),
        ('novedades', '0022_novedades_novedades_n_vehicul_f233c1_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovedadNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severidad', models.CharField(choices=[('informativo', 'Informativo'), ('accion_requerida', 'Acción requerida')], default='informativo', max_length=20)),
                ('mensaje', models.CharField(max_length=255)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_leido', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='Cliente.cliente')),
                ('novedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_cliente', to='novedades.novedades')),
            ],
            options={
                'verbose_name': 'Notificación de cliente',
                'verbose_name_plural': 'Notificaciones de cliente',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['cliente', 'leido'], name='novedades_n_cliente_5a039e_idx')],
            },
        ),
    ]
