# Generated by Django 6.0.6 on 2026-07-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0023_novedadnotificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedades',
            name='nivel_prioridad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], editable=False, max_length=50, null=True),
        ),
    ]
