"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'corsheaders',
    
    
    #Aplicaciones
    'apps.Cliente',
    'apps.configuracion',
    'apps.Informes',
    'apps.mantenimientos',
    'apps.novedades',
    'apps.usuarios_colfenix',
    'apps.Vehiculo'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   
]
# CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[])
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# El backend es solo API: si el CSRF falla, devolver JSON en vez de la
# página HTML por defecto de Django (el frontend hace res.json() sobre
# la respuesta y truena con "Unexpected token '<'" si recibe HTML).
CSRF_FAILURE_VIEW = "config.views.csrf_failure"

# Frontend y backend viven en hosts distintos cuando se prueba por túnel de
# desarrollo (VS Code Ports/devtunnels), así que las cookies de sesión y CSRF
# necesitan SameSite=None (+ Secure, obligatorio junto con None) para que el
# navegador las envíe entre esos dos hosts. En localhost esto no hace falta
# porque el puerto no afecta el alcance de las cookies. Se activa solo con
# DEV_TUNNEL=1 para no tocar el flujo normal de desarrollo local.
if env.bool('DEV_TUNNEL', default=False):
    SESSION_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SECURE = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media (evidencia adjunta a novedades e informes)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# El constructor de informes (plantillaInforme.jsx) envía las imágenes
# adjuntas (Logiox, mapa del recorrido, evidencia de eventos, mantenimientos)
# como data URLs base64 dentro de un único POST JSON, no como multipart. El
# límite por defecto de Django (2.5 MB) es para APIs normales y se supera
# fácilmente con solo 2-3 imágenes reales, aunque cada una individualmente
# respete el máximo de 2 MB que ya valida el frontend por archivo — Django
# rechaza la petición completa con 400 (RequestDataTooBig) antes de que
# llegue a la vista. Se sube a 30 MB para dar espacio a un informe con varias
# imágenes adjuntas de una vez.
DATA_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024

AUTH_USER_MODEL = 'usuarios_colfenix.UsuariosColfenix'