# Generated by Django 6.0.6 on 2026-06-17 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
        ('Vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciasMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evidencia', models.CharField(choices=[('inicial', 'Evidencia Inicial'), ('final', 'Evidencia Final')], max_length=10)),
                ('imagen_1', models.ImageField(upload_to='mantenimientos/evidencias/')),
                ('imagen_2', models.ImageField(upload_to='mantenimientos/evidencias/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evidencia de Mantenimiento',
                'verbose_name_plural': 'Evidencias de Mantenimiento',
                'db_table': 'evidencias_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO_FISICO', 'PREVENTIVO FÍSICO'), ('CORRECTIVO', 'CORRECTIVO'), ('PREVENTIVO_ONLINE', 'PREVENTIVO ONLINE'), ('GENERAL', 'GENERAL'), ('MEJORA', 'MEJORA')], max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Mantenimiento',
                'verbose_name_plural': 'Tipos de Mantenimiento',
                'db_table': 'tipo_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='DetallesMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion_realizada', models.CharField(choices=[('revision_general', 'Revisión General'), ('cambio_boton_panico', 'Cambio Botón Pánico'), ('reinicio_fisico_gps', 'Reinicio Físico GPS'), ('reprogramacion_fisica_gps', 'Reprogramación Física del GPS'), ('reconexion', 'Reconexión'), ('cambio_cableado', 'Cambio Cableado'), ('cambio_tecnologia_gps', 'Cambio Tecnología GPS'), ('cambio_tecnologia_dvr', 'Cambio Tecnología DVR'), ('cambio_gps', 'Cambio GPS'), ('cambio_simcard', 'Cambio SIMCARD'), ('cambio_fusible', 'Cambio Fusible'), ('cambio_disco_duro', 'Cambio Disco Duro'), ('cambio_dvr', 'Cambio de DVR'), ('cambio_pila', 'Cambio de Pila'), ('reconfiguracion_dvr', 'Reconfiguración DVR'), ('cambio_conector_camara', 'Cambio Conector Cámara'), ('cambio_camara', 'Cambio Cámara'), ('ajuste_camara', 'Ajuste Cámara'), ('ajuste_empalme_camara', 'Ajuste Empalme Cámara'), ('cable_en_corto', 'Cable en Corto'), ('reinstalacion', 'Reinstalación'), ('modem_sin_datos', 'Módem sin Datos'), ('desinstalacion', 'Desinstalación'), ('desmonte_dvr', 'Desmonte DVR'), ('instalacion_gps', 'Instalación GPS'), ('instalacion_video_gps', 'Instalación VIDEO-GPS'), ('instalacion_camara_frontal_derecha', 'Instalación Cámara Frontal Derecha'), ('ajuste_empalme_dvr', 'Ajuste Empalme DVR'), ('punto_corriente', 'Punto de Corriente'), ('cambio_tarjeta_secundaria', 'Cambio de Tarjeta Secundaria'), ('desvinculacion_online', 'Desvinculación Online'), ('cambio_conector', 'Cambio Conector'), ('cambio_dvr_gps', 'Cambio DVR y GPS'), ('instalacion_video', 'Instalación Video'), ('cambio_tecnologia_dvr_gps', 'Cambio Tecnología DVR y GPS'), ('cambio_punto_corriente', 'Cambio Punto Corriente')], max_length=50)),
                ('observacion_inicial', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('elemento_revisado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_mantenimiento', to='mantenimientos.elementos')),
            ],
            options={
                'verbose_name': 'Detalle de Mantenimiento',
                'verbose_name_plural': 'Detalles de Mantenimiento',
                'db_table': 'detalles_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='GrupoFlota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupoFlota', to='Cliente.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion_tecnica', models.TextField(blank=True, null=True)),
                ('estado_mantenimiento', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado')], db_index=True, default='pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='Cliente.cliente')),
                ('grupo_flota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='Vehiculo.grupoflota')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'db_table': 'mantenimientos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
