# Generated by Django 6.0.6 on 2026-06-17 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vehiculo', '0001_initial'),
        ('mantenimientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mantenimientos',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='Vehiculo.vehiculo'),
        ),
        migrations.AddField(
            model_name='evidenciasmantenimiento',
            name='mantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='mantenimientos.mantenimientos'),
        ),
        migrations.AddField(
            model_name='detallesmantenimiento',
            name='mantenimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mantenimientos.mantenimientos'),
        ),
    ]
