# Generated by Django 6.0.6 on 2026-06-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('orden', models.PositiveIntegerField(default=1)),
                ('observacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='informes/evidencias/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_informe', models.CharField(editable=False, max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En_Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], default='Pendiente', max_length=20)),
                ('pdf_generado', models.FileField(blank=True, null=True, upload_to='informes/pdf/')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
