# Generated by Django 6.0.6 on 2026-06-17 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Informes', '0001_initial'),
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='novedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='novedades.novedades'),
        ),
        migrations.AddField(
            model_name='evidenciainforme',
            name='informe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='Informes.informe'),
        ),
        migrations.AddField(
            model_name='detalleinforme',
            name='informe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Informes.informe'),
        ),
    ]
