# Generated by Django 6.0.6 on 2026-06-25 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaTipoInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria_informe', models.CharField(max_length=200, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='tipoinforme',
            name='categoria_informe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='Informes.categoriatipoinforme'),
        ),
    ]
