# Generated by Django 6.0.6 on 2026-07-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0003_categoriatipoinforme_tipoinforme_categoria_informe'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoinforme',
            name='nivel_prioridad',
            field=models.CharField(choices=[('Prioridad_Alta', 'Prioridad Alta'), ('Prioridad_Media', 'Prioridad Media'), ('Prioridad_Baja', 'Prioridad Baja')], editable=False, max_length=50, null=True),
        ),
    ]
