# Generated by Django 6.0.6 on 2026-07-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0004_tipoinforme_nivel_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoinforme',
            name='nivel_prioridad',
            field=models.CharField(choices=[('Prioridad_Alta', 'Prioridad Alta'), ('Prioridad_Media', 'Prioridad Media'), ('Prioridad_Baja', 'Prioridad Baja')], default='Prioridad_Media', help_text='Prioridad que se asignará automáticamente a las novedades que usen este tipo de informe.', max_length=50),
        ),
    ]
