# Generated by Django 6.0.6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Informes", "0005_alter_tipoinforme_nivel_prioridad"),
    ]

    operations = [

        migrations.CreateModel(
            name="TipoEvento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=150, unique=True)),
                ("plantilla", models.TextField()),
                ("requiere_descripcion", models.BooleanField(default=False)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nombre"],
            },
        ),

        migrations.AlterModelOptions(
            name="informe",
            options={"ordering": ["-fecha_creacion"]},
        ),

        migrations.RenameField(
            model_name="informe",
            old_name="codigo_informe",
            new_name="codigo",
        ),

        migrations.RenameField(
            model_name="informe",
            old_name="fecha_generacion",
            new_name="fecha_creacion",
        ),

        migrations.RenameField(
            model_name="informe",
            old_name="pdf_generado",
            new_name="pdf",
        ),

        migrations.AddField(
            model_name="informe",
            name="resultado",
            field=models.CharField(
                max_length=20,
                choices=[
                    ("Positiva", "Positiva"),
                    ("Negativa", "Negativa"),
                ],
                default="Positiva",
            ),
        ),

        migrations.AddField(
            model_name="informe",
            name="tipo_informe",
            field=models.ForeignKey(
                to="Informes.tipoinforme",
                on_delete=django.db.models.deletion.PROTECT,
                null=True,
                blank=True,
            ),
        ),

        migrations.AddField(
            model_name="informe",
            name="version",
            field=models.CharField(
                max_length=50,
                default="Versión 1",
            ),
        ),

        migrations.CreateModel(
            name="InformeLogiox",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("no_aplica", models.BooleanField(default=False)),
                ("tabla", models.JSONField(default=dict, blank=True)),
                ("imagen", models.ImageField(upload_to="informes/logiox/", blank=True, null=True)),
                (
                    "informe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logiox",
                        to="Informes.informe",
                    ),
                ),
            ],
        ),

        migrations.CreateModel(
            name="InformeRecorrido",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("no_aplica", models.BooleanField(default=False)),
                ("descripcion", models.TextField(blank=True)),
                ("imagen", models.ImageField(upload_to="informes/recorrido/", blank=True, null=True)),
                (
                    "informe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recorrido",
                        to="Informes.informe",
                    ),
                ),
            ],
        ),

        migrations.CreateModel(
            name="VideoInforme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("orden", models.PositiveIntegerField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("observacion", models.TextField(blank=True)),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="Informes.informe",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),

        migrations.CreateModel(
            name="EventoInforme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("orden", models.PositiveIntegerField()),
                ("descripcion", models.TextField(blank=True)),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="Informes.videoinforme",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Informes.tipoevento",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),

        migrations.CreateModel(
            name="EvidenciaEvento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("imagen", models.ImageField(upload_to="informes/eventos/")),
                ("descripcion", models.CharField(max_length=200, blank=True)),
                ("orden", models.PositiveIntegerField(default=1)),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="Informes.eventoinforme",
                    ),
                ),
            ],
            options={
                "ordering": ["orden"],
            },
        ),

        migrations.CreateModel(
            name="PlantillaTexto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("contenido", models.TextField(help_text="Ejemplo: Se evidencia un evento puntual entre las {inicio} y las {fin} horas.")),
                ("activo", models.BooleanField(default=True)),
                (
                    "tipo_evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plantillas",
                        to="Informes.tipoevento",
                    ),
                ),
            ],
        ),

        migrations.DeleteModel(
            name="EvidenciaInforme",
        ),
    ]