# Generated by Django 6.0.6 on 2026-07-13 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0006_eventoinforme_tipoevento_alter_informe_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoInforme',
            new_name='SegmentoAnalizado',
        ),
        migrations.RenameField(
            model_name='eventoinforme',
            old_name='video',
            new_name='segmento',
        ),
        # NOTA: el CreateModel de PlantillaTexto que traía esta migración se quitó
        # porque esa tabla ya la crea 0006 (que sí quedó aplicada) — al intentar
        # aplicar 0007 en la BD real, Postgres tronaba con "la relación ya existe".
    ]
