# Generated by Django 6.0.6 on 2026-07-13 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0007_rename_videoinforme_segmentoanalizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='resultado',
            field=models.CharField(choices=[('Positiva', 'Positiva'), ('Negativa', 'Negativa')], max_length=20),
        ),
        migrations.AlterField(
            model_name='informe',
            name='tipo_informe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Informes.tipoinforme'),
        ),
    ]
