# Generated by Django 6.0.6 on 2026-07-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0008_alter_informe_resultado_alter_informe_tipo_informe'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleinforme',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='informes/detalles/'),
        ),
        migrations.AddField(
            model_name='informe',
            name='anexos',
            field=models.TextField(blank=True, help_text="Ej. '02 clips de video con los registros de grabación.'"),
        ),
        migrations.AddField(
            model_name='informe',
            name='mantenimientos_nota',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='informe',
            name='mantenimientos_tabla',
            field=models.JSONField(blank=True, default=dict, help_text='Tabla de mantenimientos anteriores ({columnas, filas}), solo aplica a resultado Negativa.'),
        ),
        migrations.AddField(
            model_name='informe',
            name='solicitud',
            field=models.TextField(blank=True, help_text='Correo o petición original del cliente.'),
        ),
        migrations.AddField(
            model_name='informe',
            name='titulo',
            field=models.CharField(blank=True, help_text="Título del encabezado impreso, ej. 'INFORME NOVEDAD – GERENCIA JURIDICA'.", max_length=255),
        ),
        migrations.AddField(
            model_name='informerecorrido',
            name='celular',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='informerecorrido',
            name='envios',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='informerecorrido',
            name='fecha_incidente',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informerecorrido',
            name='hora_incidente',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='informerecorrido',
            name='linea',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='informerecorrido',
            name='lugar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='informerecorrido',
            name='usuarios',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='detalleinforme',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detalleinforme',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='segmentoanalizado',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='segmentoanalizado',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
