# Generated by Django 6.0.6 on 2026-07-27 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0009_detalleinforme_imagen_informe_anexos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informelogiox',
            name='modo',
            field=models.CharField(choices=[('tabla', 'Tabla'), ('imagen', 'Imagen')], default='tabla', help_text='Si el analista adjuntó una captura de Logiox en vez de construir la tabla.', max_length=10),
        ),
        migrations.CreateModel(
            name='SolicitudImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='informes/solicitud/')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_imagenes', to='Informes.informe')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
