# Generated by Django 6.0.6 on 2026-07-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0010_informelogiox_modo_solicitudimagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informerecorrido',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='informerecorrido',
            name='envios',
        ),
        migrations.RemoveField(
            model_name='informerecorrido',
            name='linea',
        ),
        migrations.RemoveField(
            model_name='informerecorrido',
            name='usuarios',
        ),
        migrations.AddField(
            model_name='informerecorrido',
            name='intro_texto',
            field=models.TextField(blank=True),
        ),
    ]
