# Generated by Django 6.0.6 on 2026-07-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0011_remove_informerecorrido_celular_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informerecorrido',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='informerecorrido',
            name='fecha_incidente',
        ),
        migrations.RemoveField(
            model_name='informerecorrido',
            name='hora_incidente',
        ),
        migrations.RemoveField(
            model_name='informerecorrido',
            name='lugar',
        ),
    ]
