# Generated by Django 6.0.6 on 2026-07-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0012_remove_informerecorrido_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='informerecorrido',
            name='texto_confirmacion',
            field=models.TextField(blank=True),
        ),
    ]
