# Generated by Django 6.0.6 on 2026-07-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0013_informerecorrido_texto_confirmacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoinforme',
            name='tiempo_maximo_horas',
            field=models.PositiveIntegerField(blank=True, help_text='Horas hábiles máximas desde ENCOLADO hasta TERMINADO. Vacío = sin SLA definido.', null=True),
        ),
    ]
