# Generated by Django 6.0.6 on 2026-07-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Informes', '0014_tipoinforme_tiempo_maximo_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoinforme',
            name='nivel_prioridad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Prioridad_Media', help_text='Prioridad que se asignará automáticamente a las novedades que usen este tipo de informe.', max_length=50),
        ),
    ]
