# Generated by Django 6.0.6 on 2026-06-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
