# Generated by Django 6.0.6 on 2026-07-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_cliente_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='abreviatura',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
