# Generated by Django 6.0.6 on 2026-07-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_area_abreviatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contacto',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
