# Generated by Django 5.2.7 on 2026-06-23 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_colfenix', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioscolfenix',
            name='rol',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
