# Generated by Django 6.0.6 on 2026-07-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_colfenix', '0002_alter_usuarioscolfenix_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioscolfenix',
            name='rol',
            field=models.CharField(blank=True, choices=[('analista', 'Analista'), ('supervisor', 'Supervisor'), ('administrador', 'Administrador')], max_length=250),
        ),
    ]
