# Generated by Django 6.0.6 on 2026-07-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_permiso'),
        ('usuarios_colfenix', '0003_alter_usuarioscolfenix_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioscolfenix',
            name='permisos',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='configuracion.permiso'),
        ),
    ]
