# Generated by Django 6.0.6 on 2026-07-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios_colfenix', '0006_permiso_gestionar_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
