# Generated by Django 6.0.6 on 2026-07-30 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_area_abreviatura'),
        ('usuarios_colfenix', '0008_seed_roles_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioscolfenix',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios_portal', to='Cliente.cliente'),
        ),
        migrations.AddField(
            model_name='usuarioscolfenix',
            name='tipo',
            field=models.CharField(choices=[('STAFF', 'Staff interno'), ('CLIENTE', 'Cliente')], default='STAFF', max_length=10),
        ),
    ]
