# Generated by Django 6.0.6 on 2026-06-17 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(db_index=True, max_length=150)),
                ('destino', models.CharField(db_index=True, max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['origen', 'destino'],
            },
        ),
        migrations.CreateModel(
            name='GrupoFlota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_flota', to='Cliente.cliente')),
            ],
            options={
                'verbose_name': 'Grupo de Flota',
                'verbose_name_plural': 'Grupos de Flota',
                'ordering': ['nombre_grupo'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_interno', models.CharField(db_index=True, max_length=20, unique=True)),
                ('placa', models.CharField(db_index=True, max_length=10, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='Cliente.cliente')),
                ('grupo_flota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_flota', to='Vehiculo.grupoflota')),
            ],
        ),
    ]
