# Generated by Django 6.0.6 on 2026-07-29 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoDVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_maquina', models.PositiveSmallIntegerField(choices=[(1, 'Máquina 1'), (2, 'Máquina 2')])),
                ('marca', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_dvr', to='Vehiculo.vehiculo')),
            ],
            options={
                'verbose_name': 'Dispositivo DVR',
                'verbose_name_plural': 'Dispositivos DVR',
                'ordering': ['vehiculo', 'numero_maquina'],
                'unique_together': {('vehiculo', 'numero_maquina')},
            },
        ),
    ]
