# Generated by Django 6.0.6 on 2026-07-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehiculo', '0002_dispositivodvr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionDVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses_caducidad_pila', models.PositiveSmallIntegerField(default=6)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='dispositivodvr',
            name='fecha_ultimo_cambio_pila',
            field=models.DateField(blank=True, null=True),
        ),
    ]
